tools:
  exceptions: https://tailor-ra.sentry.io/issues/
  logging: 
  ci: https://github.com/dcsil/tailor-app/actions

services:
  production: https://tailor-4d71417e9aab.herokuapp.com/

docs:
  getting_started: https://github.com/dcsil/tailor-app
  
commands:
  bootstrap: script/bootstrap
  server: cd frontend; npm install; npm run dev
  test: 
    frontend: cd frontend; npm test
    backend: cd backend; pytest tests/
