tools:
  exceptions: https://tailor-ra.sentry.io/issues/
  logging: 
  ci: https://github.com/dcsil/tailor-app/actions

services:
  production: 

docs:
  getting_started: https://github.com/dcsil/tailor-app
  
commands:
  bootstrap: 
  server: 
  test: 
