---
name: Python Linting

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Verify .pylintrc exists
        run: |
          echo "Checking for Pylint config file..."
          ls -la backend/.pylintrc || echo "Warning: .pylintrc not found"

      - name: Run Ruff
        run: |
          ruff check backend/
          ruff format --check backend/

      - name: Run Pylint on backend
        run: |
          pylint --rcfile=backend/.pylintrc . --disable=R0903,R0917,R0911,R0914 || true
