name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm ci
        working-directory: tailor-app/frontend

      - name: Front-end tests
        run: npm test
        working-directory: tailor-app/frontend

      - name: Back-end package installation
        run: python3 -m pip install -r requirements.txt
        working-directory: tailor-app/backend

      - name: Back-end testing
        run: python3 -m pytest tests/
        working-directory: tailor-app/backend
