name: Unit Tests

on:
    pull_request:
        branches:
            - main

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - name: npm install
              run: |
                cd tailor-app/frontend
                npm ci
            - name: front-end tests
              run: |
                cd tailor-app/frontend  
                npm test
            - name: back-end package installation
              run: |
                cd tailor-app/backend
                python3 -m pip install -r requirements.txt
            - name: back-end testing with coverage
              run: |
                cd tailor-app/backend
                python3 -m pytest tests/ --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=. | tee pytest-coverage.txt
            - name: Add coverage comment to PR
              uses: MishaKav/pytest-coverage-comment@main
              with:
                pytest-coverage-path: ./tailor-app/backend/pytest-coverage.txt
                junitxml-path: ./tailor-app/backend/pytest.xml
